

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: ldh
    password: doo
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888
elasticsearch:
  host: localhost
  port: 9200
  id: elastic
  password: dlengus

file:
  upload_dir: ./images
host:
  search: http://localhost:8080
  indexer: http://localhost:8081




