spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/shop
      username: ldh
      password: doo
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
elasticsearch:
  host: localhost
  port: 9200
  id: elastic
  password: dlengus