logging:
  level:
    root: warn
    com.etoos.imagesearch: debug
  #path: /home/ec2-user/api/log
  file:
    max-history: 7
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/doo?zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
#    username: ldh
#    password: doo
#    driver-class-name: com.mysql.jdbc.Driver
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB

#mybatis:
#  type-aliases-package: com.etoos.opencv.mapper
#  mapper-locations: classpath:mybatis/mapper/**/*.xml

server:
  port: 8080

elasticsearch:
  host: 192.168.1.14
  port: 9200
  id: elastic
  password: dlengus

aws:
  s3:
    host: s3.ap-northeast-2.amazonaws.com
    bucket: cmw-ws
    region: ap-northeast-2
    key-name: system/images
    local-file-save-path: ${HOME}
file:
  upload_dir: ./images

host:
  search: http://3.35.68.93:8080
  indexer: http://3.35.68.93:8081
